version: '3'
services:
    node:
        image: node:20.18.1-alpine3.20
        restart: always
        volumes:
            - ./:/var/www/
        working_dir: /var/www/frontend
        command: "sleep 500000"
